server:
  port: 10086
spring:
  application:
    name: spring-cloud-alibaba-dubbo-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      discovery:
        health-check-interval: 15s
        health-check-path: /hello
      host: localhost
      port: 8500

management:
  endpoints:
    web:
      exposure:
        include: '*'
